services:
  app1:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - APP_ID=app1
    networks:
      - app-network
    depends_on:
      - mongodb

  app2:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - APP_ID=app2
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "27017:27017"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/stream.d:/etc/nginx/stream.d:ro
    depends_on:
      - app1
      - app2
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 