services:
  app1:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - APP_ID=app1
    networks:
      - app-network
    depends_on:
      - mongodb

  app2:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - APP_ID=app2
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "27017:27017"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/stream.d:/etc/nginx/stream.d:ro
    depends_on:
      - app1
      - app2
      - mongodb
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 